################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################

if (NOT MSVC)
    include(FindPkgConfig)
    pkg_check_modules(PC_FTY-PROTO "libfty_proto")
    if (NOT PC_FTY-PROTO_FOUND)
        pkg_check_modules(PC_FTY-PROTO "libfty_proto")
    endif (NOT PC_FTY-PROTO_FOUND)
    if (PC_FTY-PROTO_FOUND)
        # add CFLAGS from pkg-config file, e.g. draft api.
        add_definitions(${PC_FTY-PROTO_CFLAGS} ${PC_FTY-PROTO_CFLAGS_OTHER})
        # some libraries install the headers is a subdirectory of the include dir
        # returned by pkg-config, so use a wildcard match to improve chances of finding
        # headers and SOs.
        set(PC_FTY-PROTO_INCLUDE_HINTS ${PC_FTY-PROTO_INCLUDE_DIRS} ${PC_FTY-PROTO_INCLUDE_DIRS}/*)
        set(PC_FTY-PROTO_LIBRARY_HINTS ${PC_FTY-PROTO_LIBRARY_DIRS} ${PC_FTY-PROTO_LIBRARY_DIRS}/*)
    endif(PC_FTY-PROTO_FOUND)
endif (NOT MSVC)

find_path (
    FTY-PROTO_INCLUDE_DIRS
    NAMES ftyproto.h
    HINTS ${PC_FTY-PROTO_INCLUDE_HINTS}
)

find_library (
    FTY-PROTO_LIBRARIES
    NAMES fty-proto
    HINTS ${PC_FTY-PROTO_LIBRARY_HINTS}
)

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(
    FTY-PROTO
    REQUIRED_VARS FTY-PROTO_LIBRARIES FTY-PROTO_INCLUDE_DIRS
)
mark_as_advanced(
    FTY-PROTO_FOUND
    FTY-PROTO_LIBRARIES FTY-PROTO_INCLUDE_DIRS
)

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
