#!/usr/bin/env bash
set -ex


# keep an eye on git version used by CI
git --version
if [[ $(git --no-pager diff -w api/*) ]]; then
    git --no-pager diff -w api/*
    echo "There are diffs between current code and code generated by zproto!"
    exit 1
fi
if [[ $(git status -s api) ]]; then
    git status -s api
    echo "zproto generated new files!"
    exit 1
fi
