/*  =========================================================================
    uptime - UPTIME wrapper

    Copyright (C) 2014 - 2015 Eaton                                        
                                                                           
    This program is free software; you can redistribute it and/or modify   
    it under the terms of the GNU General Public License as published by   
    the Free Software Foundation; either version 2 of the License, or      
    (at your option) any later version.                                    
                                                                           
    This program is distributed in the hope that it will be useful,        
    but WITHOUT ANY WARRANTY; without even the implied warranty of         
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          
    GNU General Public License for more details.                           
                                                                           
    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.            

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
    =========================================================================
*/

#ifndef UPT_LIBRARY_H_INCLUDED
#define UPT_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <czmq.h>
#include <malamute.h>
#include <biosproto.h>

//  UPTIME version macros for compile-time API detection

#define UPTIME_VERSION_MAJOR 0
#define UPTIME_VERSION_MINOR 0
#define UPTIME_VERSION_PATCH 0

#define UPTIME_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define UPTIME_VERSION \
    UPTIME_MAKE_VERSION(UPTIME_VERSION_MAJOR, UPTIME_VERSION_MINOR, UPTIME_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined LIBUPT_STATIC
#       define UPT_EXPORT
#   elif defined LIBUPT_EXPORTS
#       define UPT_EXPORT __declspec(dllexport)
#   else
#       define UPT_EXPORT __declspec(dllimport)
#   endif
#else
#   define UPT_EXPORT
#endif

//  Opaque class structures to allow forward references
typedef struct _upt_server_t upt_server_t;
#define UPT_SERVER_T_DEFINED


//  Public API classes
#include "upt_server.h"

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
